### ISSUE TITLE
Any chance to get an ARM build?

### ISSUE THREAD

**Issue by avraham** [Apipa169/Assistant-Relay-Docker#1]
Any chance to get an ARM build?
Thanks

**Comment by Apipa169** [comment]
Not at the moment, but what you can do is running the build for hass.io, which will also work stand alone. The only difference is that you have to mount /data instead of the other two volumes. 

https://hub.docker.com/repository/docker/apipa169/armv7-hassio-assistant_relay

**Comment by avraham** [comment]
Thank you, that worked perfectly.
