### ISSUE TITLE
500 Error from Home Assistant container to Relay container via HA Rest Command

### ISSUE THREAD

**Issue by chadbaum** [Apipa169/Assistant-Relay-Docker#8]
Able to set up everything on the Relay side in a docker and it works fine in sandbox.  However, I am unable to get HA to send a valid request to it, as I get a 500 error everytime.  Assuming there is some networking issue I am not accounting for.  Below are my relevant settings:

HA LOG ERROR
Error. Url: http://192.168.4.100:4949/assistant. Status code 500. Payload: b'{"command":"test", "user":"chad", "broadcast":true}'

HA CONFIG
`rest_command:
  assistant_relay:
    url: http://192.168.4.100:4949/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ message }}", "user":"chad"}'
  assistant_broadcast:
    url: http://192.168.4.100:4949/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ message }}", "user":"chad", "broadcast":true}'`

RELAY DOCKER-COMPOSE
`assistant-relay:
    container_name: assistant_relay
    ports:
      - 4949:4949
    volumes:
      - /docker/assistant-relay/config/config.json:/assistant_relay/bin/config.json:rw
      - /docker/assistant-relay/config/audio-responses:/assistant_relay/bin/audio-responses:rw
    image: apipa169/assistant-relay:latest
    restart: unless-stopped`

Relay config json has the port 4949.

**Comment by Apipa169** [comment]
What do you see in de log of the container?

**Comment by chadbaum** [comment]
Hmm, I just checked and now the sandbox isn't working anymore.  It was before, with all commands.  Here is the pertinent error:

0|www  | POST /assistant 500 37.017 ms - 44
0|www  | POST /server/getConfig 200 108.719 ms - 126
0|www  | TypeError: Cannot read property 'converse' of undefined
0|www  |     at new Conversation (/assistant_relay/node_modules/google-assistant/components/conversation.js:136:34)
0|www  |     at /assistant_relay/helpers/assistant.js:19:38
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /assistant 500 23.157 ms - 44

Not sure if it's the cause of the other issue, as it was not doing this before.  Thanks!

**Comment by Apipa169** [comment]
You might have downloaded the wrong token from google.

The steps in de GUI of Assistant Relay are not 100% in line with the actual steps on the google website.

**Comment by chadbaum** [comment]
So I just deleted my user account, restarted the relay container, and re-set up my account.  I'm able to use sandbox again and everything works in there.  But when I try to access the API from HA using the rest_command, I still get a 500 with this error:

0|www  | TypeError: Cannot read property 'converse' of undefined
0|www  |     at new Conversation (/assistant_relay/node_modules/google-assistant/components/conversation.js:136:34)
0|www  |     at /assistant_relay/helpers/assistant.js:19:38
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /assistant 500 22.518 ms - 44

**Comment by chadbaum** [comment]
Going to specify converse as false in the payload and try it.  Maybe it needs to be manually set unlike what the instructions indicate.

**Comment by chadbaum** [comment]
No dice, even with converse manually set to false in the HA rest_command payload, it still presents the same 500 error.

**Comment by chadbaum** [comment]
Nevermind, I'm dumb.  My user name was not capitalized correctly in HA payload and that is why it was failing.  Thanks for helping me through this failure.  :)
